spring:
    application:
       name: ^project.artifactId^
    main:
        allow-bean-definition-overriding: true
        banner-mode: log
    codec:
        max-in-memory-size: 100MB
    aop:
        proxy-target-class: false
    threads:
        virtual:
            enabled: true
    cloud:
        kubernetes:
            discovery:
                all-namespaces: true
    reactor:
        context-propagation: auto

    #Data source config
    data:
     mongodb:
        host: localhost
        username: admin
        password: admin
        database: application
        authentication-database: application
        auto-index-creation: true

    kafka:
        bootstrap-servers: localhost:9092
        admin:
            auto-create: true
server:
    port: 8081

management:
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        env:
            enabled: true
    zipkin:
        tracing:
            endpoint: localhost:9411/api/v2/spans
    otlp:
        metrics:
            export:
                url: localhost:4318/v1/traces
    tracing:
        enabled: true
        sampling:
            probability: 1
        propagation:
                type: b3

#Logging configuration
logging:
    pattern:
        file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([%5L]){magenta} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
        console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([%5L]){magenta} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
        level: '%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]'

    file:
        name: /var/log/java-services/${spring.application.name}.log
        path: /var/log/java-services/
    logback:
        rollingPolicy:
            max-history: 180
            max-file-size: 1024MB
            file-name-pattern: /var/log/java-services/${spring.application.name}-%d{yyyy-ww}.%i.log

#Meta Data Configuration
info:
    tags:
        environment: ${spring.profiles.active}
    app:
        name: ^project.name^
        version: ^project.version^
        description: ^project.description^
        spring-boot-version: ${spring-boot.version}
        spring-cloud-version: ^spring-cloud.version^
        environment: ${spring.profiles.active}
        swagger-url: <a target='_blank' href='http://${spring.cloud.client.hostname}:${server.port}/swagger-ui.html'>http://${spring.cloud.client.hostname}:${server.port}/swagger-ui.html</a>

#swagger config
springdoc:
    writer-with-default-pretty-printer: true
    swagger-ui:
        operations-sorter: method

topic:
   los:
     application-request-updates: los-application-request-updates

---
spring:
    config:
        activate:
            on-profile: dev
    data:
        mongodb:
            uri: mongodb://mongodb.dev-mongodb.svc.cluster.local:27017/application
    kafka:
        bootstrap-servers: kafka.dev-kafka.svc.cluster.local:9092

management:
    otlp:
        metrics:
            export:
                url: jaeger.dev-jaeger.svc.cluster.local:4318/v1/traces
    zipkin:
        tracing:
            endpoint: zipkin.dev-zipkin.svc.cluster.local:9411/api/v2/spans
