name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: name:Checkout code
        uses: actions/checkout@v3

      - name: Extract Repository Name
        id: extract_repo_name
        run: |
          repo_name=$(echo "${{ github.repository }}" | awk -F'/' '{gsub(/\.git$/, "", $NF); print $NF}')
          echo "::set-output name=repo_name::$repo_name"
      - name: Set up Java 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build JAR with Maven
        run: mvn clean install -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jaganreddy17/${{ steps.extract_repo_name.outputs.repo_name }}:latest
