name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: name:Checkout code
        uses: actions/checkout@v3

      - name: Extract Repository Name
        id: extract_repo_name
        run: |
          repo_name=$(echo "${{ github.repository }}" | awk -F'/' '{gsub(/\.git$/, "", $NF); print $NF}')
          echo "::set-output name=repo_name::$repo_name"

      - name: Set up Java 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build JAR with Maven
        run: mvn clean install -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current tag from environment variable
        id: get_tag
        run: echo "::set-output name=tag::${{ env.CURRENT_TAG }}"

      - name: Increment tag value by 1
        id: increment_tag
        run: echo "::set-output name=tag::$((${{ steps.get_tag.outputs.tag }} + 1))"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jaganreddy17/${{ steps.extract_repo_name.outputs.repo_name }}:${{ steps.increment_tag.outputs.tag }}

      - name: Set incremented tag to CURRENT_TAG
        if: success()
        run: echo "CURRENT_TAG=${{ steps.increment_tag.outputs.tag }}" >> $GITHUB_ENV

      - name: update image tag info in helm chart to
        uses: actions/checkout@v3
        with:
          repository: jbaddam17/loanoriginx-ci-cd  # Replace with the actual values.yaml repo URL
          ref: main

      - name: Update app tag in values.yaml
        if: success()
        run: |
          sed -i "s/tag:.*/tag: \"${{ steps.increment_tag.outputs.tag }}\"/" ${{ steps.extract_repo_name.outputs.repo_name }}/values.yaml
          git config --global user.email "jbaddam17@gmail.com"
          git config --global user.name "jbaddam17"
          git config --global user.password ${{ secrets.GIT_PASSWORD }}
          git add ${{ steps.extract_repo_name.outputs.repo_name }}/values.yaml
          git commit -m "Update newly built app tag to chart for argo cd to pickup and deploy in cluster"
          git push
